### ISSUE TITLE
MinSdk to 21

### ISSUE THREAD

**Issue by wakaztahir** [chRyNaN/navigation#3]
Jetpack Compose min sdk version is 21 and this library should also support min sdk version 21

The library is also missing functions like push and pop , I created my own push by using duplicate Strategy of Add to Stack

Could you please fix this fast , My app is currntnly increasing its min SDK version to be able to use this library

**Comment by wakaztahir** [comment]
please update

**Comment by chRyNaN** [comment]
Thanks for bringing this up, I will address this in the upcoming release. I am finishing up tests and hope to have the release out this week.

**Comment by chRyNaN** [comment]
As for push/pop functionality, those are provided by the `goTo/goBack` functions on the `Navigator` instance. The `goTo` function acts as a "push" stack operation and the `goBack` function can act as a "pop" stack operation (although it can be more complex as there is the notion of "contexts").

**Comment by chRyNaN** [comment]
The minimum Android version has been lowered to `21` with the latest release: https://github.com/chRyNaN/navigation/releases/tag/0.8.0
