### ISSUE TITLE
Document Nested Navigation

### ISSUE THREAD

**Issue by wakaztahir** [chRyNaN/navigation#5]
I love the library for its simplicity , I hope it keeps that with its updates but there's very little documentation of nested navigation

**Comment by chRyNaN** [comment]
Nested navigation is supported through the concept of `Context`. I will add more detailed documentation with the upcoming release.

**Comment by chRyNaN** [comment]
I added information on nested navigation within the [Best Practices](https://github.com/chRyNaN/navigation/tree/0.8.0#best-practices) section of the README file
