### ISSUE TITLE
Overload resolution ambiguity for goTo function

### ISSUE THREAD

**Issue by wakaztahir** [chRyNaN/navigation#6]
Overload resolution ambiguity. All these functions match. in IDE:

public fun <Destination : NavigationDestination /* = Any */, Context : NavigationContext<TypeVariable(Destination)>> Navigator<TypeVariable(Destination), TypeVariable(Context)>.goTo(destination: TypeVariable(Destination)): Boolean defined in com.chrynan.navigation
public fun <Destination : Any, Context : NavigationContext<TypeVariable(Destination)>> Navigator<TypeVariable(Destination), TypeVariable(Context)>.goTo(destination: TypeVariable(Destination)): Unit defined in com.chrynan.navigation

also to use dispatch , the constructors for Forward Event or Backward Event Destination are internal or private , so dispatch can't be used

**Comment by wakaztahir** [comment]
Actually I was using fork now that I've replaced it with original dep , its causing issue , investigating further

**Comment by chRyNaN** [comment]
A couple points of note here:

* There are two `NavigationDestination` functions: one for a context and destination and the other for a `SingleNavigationContext` and a destination. To let the compiler know which one to use, explicitly specify the parameter names.

```kotlin
NavigationDestination(...) { destination -> ... }
// Or
NavigationDestination(...) { context, destination -> ... }
```
* The `dispatch` function is not meant to be invoked from outside of the library's internal code. That is why the `NavigationEvent` constructors are `internal`. Instead, use the appropriate `go*` function (ex: `goBack`, `goTo`, or `changeContext`).
